/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KonturLogo {
        /**
          * Full size logo or compact
         */
        "compact": boolean;
        "height": number;
        "palette": 'colorful' | 'dark' | 'light' | 'contrast';
    }
    interface KonturSpinner {
        /**
          * Dashes pattern
         */
        "dashes": string;
        /**
          * Animation frame
         */
        "frame": string;
        /**
          * Animation size
         */
        "size": number;
        /**
          * Animation speed
         */
        "speed": number;
    }
}
declare global {
    interface HTMLKonturLogoElement extends Components.KonturLogo, HTMLStencilElement {
    }
    var HTMLKonturLogoElement: {
        prototype: HTMLKonturLogoElement;
        new (): HTMLKonturLogoElement;
    };
    interface HTMLKonturSpinnerElement extends Components.KonturSpinner, HTMLStencilElement {
    }
    var HTMLKonturSpinnerElement: {
        prototype: HTMLKonturSpinnerElement;
        new (): HTMLKonturSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "kontur-logo": HTMLKonturLogoElement;
        "kontur-spinner": HTMLKonturSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface KonturLogo {
        /**
          * Full size logo or compact
         */
        "compact"?: boolean;
        "height"?: number;
        "palette"?: 'colorful' | 'dark' | 'light' | 'contrast';
    }
    interface KonturSpinner {
        /**
          * Dashes pattern
         */
        "dashes"?: string;
        /**
          * Animation frame
         */
        "frame"?: string;
        /**
          * Animation size
         */
        "size"?: number;
        /**
          * Animation speed
         */
        "speed"?: number;
    }
    interface IntrinsicElements {
        "kontur-logo": KonturLogo;
        "kontur-spinner": KonturSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kontur-logo": LocalJSX.KonturLogo & JSXBase.HTMLAttributes<HTMLKonturLogoElement>;
            "kontur-spinner": LocalJSX.KonturSpinner & JSXBase.HTMLAttributes<HTMLKonturSpinnerElement>;
        }
    }
}
