/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface KonturSpinner {
        /**
          * Dashes pattern
         */
        "dashes": string;
        /**
          * Animation frame
         */
        "frame": string;
        /**
          * Animation speed
         */
        "speed": number;
    }
}
declare global {
    interface HTMLKonturSpinnerElement extends Components.KonturSpinner, HTMLStencilElement {
    }
    var HTMLKonturSpinnerElement: {
        prototype: HTMLKonturSpinnerElement;
        new (): HTMLKonturSpinnerElement;
    };
    interface HTMLElementTagNameMap {
        "kontur-spinner": HTMLKonturSpinnerElement;
    }
}
declare namespace LocalJSX {
    interface KonturSpinner {
        /**
          * Dashes pattern
         */
        "dashes"?: string;
        /**
          * Animation frame
         */
        "frame"?: string;
        /**
          * Animation speed
         */
        "speed"?: number;
    }
    interface IntrinsicElements {
        "kontur-spinner": KonturSpinner;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "kontur-spinner": LocalJSX.KonturSpinner & JSXBase.HTMLAttributes<HTMLKonturSpinnerElement>;
        }
    }
}
